version: 2

models:
  - name: stg_telegram_messages
    description: "Cleaned and prepared Telegram messages data."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: message_text
        description: "Coalesced text or message field."
      - name: message_length
        tests:
          - not_null
      - name: has_image
        description: "Boolean flag if image exists."

  - name: stg_yolo_detections
    description: "Cleaned YOLOv8 detection results."
    columns:
      - name: message_id
        tests:
          - not_null
      - name: detected_object_class
        tests:
          - not_null
      - name: confidence_score
