version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env # This line correctly points to your .env file
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      # These values will now be loaded from your .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} # It's also good practice to make this configurable
    ports:
      - "5432:5432"